[project]
name = "bob"
version = "0.1.0"
description = "A python build system."
readme = "README.md"
requires-python = ">=3.9"
license = "MIT"

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"
